package com.fiap.bank.atm.presentation;

public enum EstadoTela {
    BEM_VINDO,
    DIGITAR_SENHA,
    MENU_PRINCIPAL,
    SELECIONAR_SAQUE,
    SAQUE_PERSONALIZADO,
    DIGITAR_DEPOSITO,
    TRANSFERENCIA_CONTA,
    TRANSFERENCIA_VALOR,
    EXIBIR_SALDO,
    EXIBIR_EXTRATO,
    ANIMACAO_SAQUE,
    ANIMACAO_IMPRESSAO,
    ANIMACAO_DEPOSITO,
    SUCESSO,
    ERRO
}
